#!/bin/bash

if [[ $1 =~ ^(-h|--help)$ ]]; then
  echo "RipSed - a wrapper around GNU sed that allows recursive replace."
  echo "Usage: rsed [-i] <s/this/that/g> <directory>"
  echo "where <directory> is a directory under which to search all"
  echo "non-hidden, non-binary files."
  echo "Options:"
  echo "-h | --help: show this page and exit"
  exit 0
fi

args=("$@")
dir="${args: -1}"
files=$(find . -not -path '*/.*')
sedargs="${args[@]:0:${#args[@]}-1}"

first="${args[0]}"
if [[ $first = "-i" ]]; then
  sedstr="${args[@]:1:${#args[@]}-2}";
else
  sedstr="${args[@]:0:${#args[@]}-1}";
fi

IFS='/' read -r -a search_arr <<< "$sedstr"
to_search="${search_arr[1]}"

rg_res=$(rg -l $to_search)
gsed ${sedargs[@]} $rg_res


